### ISSUE TITLE
error when running TinyImageNet dataset

### ISSUE THREAD

**Issue by skdearstranger** [rshaojimmy/ECCV2020-OSAD#3]
when running TinyImageNet dataset，I get a dimension mismatch error at ‘lossRec = criterionRec(recon, orig)’，in train.py, line 100.
I think the network structure for TinyImageNet should be different from the other two datasets since the difference in input image size.
Hope the author can release the correct code of TinyImageNet. Thanks.

**Comment by rshaojimmy** [comment]
Hi,

Thanks for your interest in our work!

We will update the code with our journal version soon.

Stay tuned!

**Comment by rshaojimmy** [comment]
Hi, please refer to our updated repo for extension of ECCV2020 as follows:
https://github.com/rshaojimmy/IJCV2022-OSDN-CAML/blob/main/models/DenoiseResnet.py

Thanks.
